[package]
name = "Nu_scale"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.15"
egui = "0.22"
eframe = { version = "0.22.0", features = ["wgpu"] }
opencv = { version = "0.75", optional = true }
image = "0.24"
anyhow = "1.0"
thiserror = "1.0"
once_cell = "1.17"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
global-hotkey = "0.2"
hotkey = "0.3"

[features]
default = []
capture_opencv = ["opencv"]

# Windows-specific dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_Security",
] }

# Linux-specific dependencies
[target.'cfg(unix)'.dependencies]
x11rb = { version = "0.11", features = ["all-extensions"] }
wayland-client = "0.30"
wayland-protocols = { version = "0.30", features = ["client"] }
