[package]
name = "Nu_scale"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.15"
egui = "0.22"
eframe = "0.22"
opencv = "0.75"
image = "0.24"
anyhow = "1.0"
thiserror = "1.0"
once_cell = "1.17"
qmetaobject = "0.2"
cpp_core = "0.6"
qt_core = "0.5"
qt_gui = "0.5"
qt_widgets = "0.5"
qt_ui_tools = "0.5"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
global-hotkey = "0.2"
hotkey = "0.3"

# Windows-specific dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_Security",
] }

# Linux-specific dependencies
[target.'cfg(unix)'.dependencies]
x11rb = { version = "0.11", features = ["all-extensions"] }
wayland-client = "0.30"
wayland-protocols = { version = "0.30", features = ["client"] }
