// This allows the generated bindings to be quite large
#![allow(clippy::all)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// Include the bindings generated by bindgen from `build.rs`
// The actual name `fsr3_bindings.rs` comes from the `write_to_file` call in `build.rs`
include!(concat!(env!("OUT_DIR"), "/fsr3_bindings.rs"));

// You can add helper functions or safer wrappers around the raw FFI bindings here if needed. 