[package]
name = "pyo3_numpy_test"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyo3_numpy_test"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "numpy"] } 