[package]
name = "nu_scaler_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
pyo3 = { version = "0.20", features = ["extension-module"] }
wgpu = "0.19"
