[package]
name = "nu_scaler_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
pyo3 = { version = "0.20", features = ["extension-module"] }
wgpu = "0.19"
scrap = "0.5"
windows = { version = "0.52", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }
image = "0.25"
x11 = { version = "2.21", optional = true }
bytemuck = "1.14"
pollster = "0.3"
once_cell = "1.19"
rayon = "1.8"

[build-dependencies]
# ... existing build dependencies ...
