name: Laravel Lint and Test

on:
  pull_request:
    branches: [ main, testing ]
    paths:
      - '@web/server/laravel_app/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
    
    - uses: actions/checkout@v3
    
    - name: Set up Laravel environment
      working-directory: ./@web/server/laravel_app
      run: |
        cp .env.example .env
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress
        php artisan key:generate
        
        # Create empty Vite manifest for tests
        mkdir -p public/build
        echo '{}' > public/build/manifest.json
        
        # Set up test database
        touch database/database.sqlite
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=database/database.sqlite" >> .env
    
    - name: Check code style
      working-directory: ./@web/server/laravel_app
      run: |
        if [ -f .php-cs-fixer.php ]; then
          ./vendor/bin/php-cs-fixer fix --dry-run --diff
        fi
    
    - name: Run tests
      working-directory: ./@web/server/laravel_app
      run: |
        php artisan test --env=testing 